### PR TITLE
fix:multi lock calls cannot reset body style in android

### PR DESCRIPTION
**Pull request by feitiange**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bug fix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

**The PR fulfills these requirements:**
multi lock function calls cannot reset body style in android

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following platforms: (Providing a detailed version will be better.)

- [x] PC
- [x] iOS
- [x] Android

If it's convenient:

* Add an online address:
  * codepen: https://codepen.io/
  * jsfiddle: https://jsfiddle.net/
  * codesandbox: https://codesandbox.io/
* Add a repository：https://github.com/new

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by BuptStEve** [comment]
能提供个复现 bug 的在线 demo么？

* codepen: https://codepen.io/
* jsfiddle: https://jsfiddle.net/
* codesandbox: https://codesandbox.io/

**Comment by feitiange** [comment]
大概这样？就是多个元素都要保留滑动但是body停止的情况，https://codesandbox.io/s/mor5o68jp?fontsize=14

**Comment by BuptStEve** [comment]
> 大概这样？就是多个元素都要保留滑动但是body停止的情况，https://codesandbox.io/s/mor5o68jp?fontsize=14

确实是在多次调用时有问题，这个问题其实有想到，只是没考虑周全。 👍

**Comment by BuptStEve** [comment]
@all-contributors add @feitiange for bug

**Pull request merged**
